### ISSUE TITLE
I'm getting the error.

### ISSUE THREAD

**Issue by xploregopi** [codyseibert/tab-tracker#1]
/var/www/html/tab_tracker/server$ npm start

> server@1.0.0 start /var/www/html/tab_tracker/server
> ./node_modules/nodemon/bin/nodemon.js src/app.js --exec 'npm run lint && node'

[nodemon] 1.11.0
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `npm run lint && node src/app.js`

> server@1.0.0 lint /var/www/html/tab_tracker/server
> true || ./node_modules/.bin/eslint **/*.js

/var/www/html/tab_tracker/server/src/passport.js:13
  }, async function (jwtPayload, done) {
     ^^^^^

SyntaxError: missing ) after argument list
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/var/www/html/tab_tracker/server/src/app.js:13:1)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:502:3
[nodemon] app crashed - waiting for file changes before starting...

**Comment by codyseibert** [comment]
What version of node are you using?  You should at least be at version 8.2.1

**Comment by xploregopi** [comment]
Node => v6.11.3.

**Comment by MHGamingBD** [comment]
i am getting this error when try to install vue-cli i am using latest version of node

C:\Users\Aaus\Desktop\hassan>npm install -g vue-cli
npm WARN deprecated babel-preset-latest@6.24.1: We're super 😸  excited that you're trying to use ES2017+ syntax, but instead of making more yearly presets 😭 , Babel now has a better preset that we recommend you use instead: npm install babel-preset-env --save-dev. preset-env without options will compile ES2015+ down to ES5 just like using all the presets together and thus is more future proof. It also allows you to target specific browsers so that Babel can do less work and you can ship native ES2015+ to user 😎 ! We are also in the process of releasing v7, so please give http://babeljs.io/blog/2017/09/12/planning-for-7.0 a read and help test it out in beta! Thanks so much for using Babel 🙏, please give us a follow on Twitter @babeljs for news on Babel, join slack.babeljs.io for discussion/development and help support the project at opencollective.com/babel
npm WARN deprecated babel-preset-es2016@6.24.1: We're super 😸  excited that you're trying to use ES2016 syntax, but instead of making more yearly presets 😭 , Babel now has a better preset that we recommend you use instead: npm install babel-preset-env --save-dev. preset-env without options will compile ES2015+ down to ES5 just like using all the presets together and thus is more future proof. It also allows you to target specific browsers so that Babel can do less work and you can ship native ES2015+ to user 😎 ! We are also in the process of releasing v7, so please give http://babeljs.io/blog/2017/09/12/planning-for-7.0 a read and help test it out in beta! Thanks so much for using Babel 🙏, please give us a follow on Twitter @babeljs for news on Babel, join slack.babeljs.io for discussion/development and help support the project at opencollective.com/babel
npm WARN deprecated babel-preset-es2017@6.24.1: We're super 😸  excited that you're trying to use ES2017 syntax, but instead of making more yearly presets 😭 , Babel now has a better preset that we recommend you use instead: npm install babel-preset-env --save-dev. preset-env without options will compile ES2015+ down to ES5 just like using all the presets together and thus is more future proof. It also allows you to target specific browsers so that Babel can do less work and you can ship native ES2015+ to user 😎 ! We are also in the process of releasing v7, so please give http://babeljs.io/blog/2017/09/12/planning-for-7.0 a read and help test it out in beta! Thanks so much for using Babel 🙏, please give us a follow on Twitter @babeljs for news on Babel, join slack.babeljs.io for discussion/development and help support the project at opencollective.com/babel
npm WARN deprecated babel-preset-es2015@6.24.1: We're super 😸  excited that you're trying to use ES2015 syntax, but instead of making more yearly presets 😭 , Babel now has a better preset that we recommend you use instead: npm install babel-preset-env --save-dev. preset-env without options will compile ES2015+ down to ES5 just like using all the presets together and thus is more future proof. It also allows you to target specific browsers so that Babel can do less work and you can ship native ES2015+ to user 😎 ! We are also in the process of releasing v7, so please give http://babeljs.io/blog/2017/09/12/planning-for-7.0 a read and help test it out in beta! Thanks so much for using Babel 🙏, please give us a follow on Twitter @babeljs for news on Babel, join slack.babeljs.io for discussion/development and help support the project at opencollective.com/babel
[            ......] | build: verb linkMans js-beautify@1.7.0[            ......] | build: verb linkMans js-beautify@1.7[            ......] | build: verb linkMans js-beautify@1.7.0[            ......] | build: verb linkMans js-beautify@npm WARN Error: EPERM: operation not permitted, scandir 'C:\Users\Aaus\AppData\Roaming\npm\node_modules\vue-cli\node_modules\fsevents\node_modules\getpass\node_modules'
npm WARN  { Error: EPERM: operation not permitted, scandir 'C:\Users\Aaus\AppData\Roaming\npm\node_modules\vue-cli\node_modules\fsevents\node_modules\getpass\node_modules'
npm WARN   stack: 'Error: EPERM: operation not permitted, scandir \'C:\\Users\\Aaus\\AppData\\Roaming\\npm\\node_modules\\vue-cli\\node_modules\\fsevents\\node_modules\\getpass\\node_modules\'',
npm WARN   errno: -4048,
npm WARN   code: 'EPERM',
npm WARN   syscall: 'scandir',
npm WARN   path: 'C:\\Users\\Aaus\\AppData\\Roaming\\npm\\node_modules\\vue-cli\\node_modules\\fsevents\\node_modules\\getpass\\node_modules' }
npm ERR! path C:\Users\Aaus\AppData\Roaming\npm\node_modules\vue-cli\node_modules\js-beautify\js\bin\css-beautify.js
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall chmod
npm ERR! enoent ENOENT: no such file or directory, chmod 'C:\Users\Aaus\AppData\Roaming\npm\node_modules\vue-cli\node_modules\js-beautify\js\bin\css-beautify.js'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Aaus\AppData\Roaming\npm-cache\_logs\2017-09-18T11_03_52_599Z-debug.log

**Comment by Alaev** [comment]
try to update to node 8+
