### ISSUE TITLE
SyntaxError: missing ) after argument list

### ISSUE THREAD

**Issue by IslandDuck** [codyseibert/tab-tracker#25]
**After running** _npm start_ **on the** _server_ **dir, I get a syntax  error message** _"SyntaxError: missing ) after argument list"_, **pointing to** _tab-tracker/server/src/passport.js_ **file. Here is the full error message from my console:** 

/home/ubuntu/workspace/tab-tracker/server/src/passport.js:13
  }, async function (jwtPayload, done) {
     ^^^^^

SyntaxError: missing ) after argument list
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/ubuntu/workspace/tab-tracker/server/src/app.js:13:1)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:504:3
[nodemon] app crashed - waiting for file changes before starting...

**I put the source code of **tab-tracker/server/src/passport.js** file into JSLint and got this Warning:**

Expected ')' to match '(' from line 9 and instead saw 'function'.
  _}, async function (jwtPayload, done) {_

**Can someone help solve the issue please? Thank you**

**Comment by IslandDuck** [comment]
Found the issue. I'm using Node Version Manager and forgot to switch to a Node version that supports ES6. Hence the error.
